---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# calcal

<!-- badges: start -->
<!-- badges: end -->

The goal of calcal is to do calendrical calculations, based on the algorithms described in [Reingold and
    Dershowitz (2018) *Calendrical Calculations*, 4th edition, Cambridge University Press](https://doi.org/10.1017/9781107415058).

## Installation

You can install the development version of calcal from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("robjhyndman/calcal")
```

## Example

Today's date in multiple calendars:


```{r example}
library(calcal)
today <- Sys.Date()
as_rd(today)
as_gregorian(today)
```

Some US holidays

```{r holidays}
c(
  us_independence_day(2025),
  us_labor_day(2025),
  us_memorial_day(2025),
  us_election_day(2025),
  us_daylight_saving_start(2025),
  us_daylight_saving_end(2025),
  christmas(2025),
  advent(2025),
  epiphany(2025)
)
```
