test_that("rd_fixed", {
  expect_error(rd_fixed("2020-02-02"))
  expect_equal(vctrs::vec_cast(rd_fixed(1234567), numeric()), 1234567)
  expect_true(as_rd(50) > as_rd(49))
  expect_true(as_rd(50) >= as_rd(50))
  expect_true(as_rd(50) < as_rd(51))
  expect_true(as_rd(50) <= as_rd(50))
  expect_true(as_rd(50) == as_rd(50))
  expect_equal(as_rd(50) + 5, as_rd(55))
  expect_equal(as_rd(50) - 5, as_rd(45))
  expect_equal(as_rd(50) - as_rd(45), 5)
  expect_error(as_rd(50) + as_rd(2))
  expect_equal(vec_cast(1, rd_fixed()), rd_fixed(1))
  expect_equal(rd_fixed(1L), rd_fixed(1))
  expect_equal(vec_cast(rd_fixed(1), integer()), 1L)
  expect_equal(vec_cast(rd_fixed(1), double()), 1)
  expect_no_error(as_rd(NA_integer_))
})
